from app.models import db, Genre

def seed_genres():
  genre1 = Genre(name='Fantasy')
  genre2 = Genre(name='Adventure')
  genre3 = Genre(name='History')
  genre4 = Genre(name='Science Fiction')
  genre5 = Genre(name='Historical Fiction')
  genre6 = Genre(name='HISTORY & BIOGRAPHY')
  genre7 = Genre(name='Art')
  genre8 = Genre(name='Manga')
  genre9 = Genre(name='Apocalyptic')
  genre10 = Genre(name='Biography')
  genre11 = Genre(name='Business')
  genre12 = Genre(name='Music')
  genre13 = Genre(name="Chidlren's")
  genre14 = Genre(name='Nonfiction')
  genre15 = Genre(name='Christian')
  genre16 = Genre(name='Paranormal')
  genre17 = Genre(name='Classics')
  genre18 = Genre(name='Poetry')
  genre19 = Genre(name='Comics')
  genre20 = Genre(name='Contemporary')
  genre21 = Genre(name='Psycology')
  genre22 = Genre(name='CookBooks')
  genre23 = Genre(name='Religion')
  genre25 = Genre(name='Romance')
  genre28 = Genre(name='Fiction')
  genre29 = Genre(name='Self Help')
  genre32 = Genre(name='Spirituality')
  genre33 = Genre(name='Thriller')
  genre34 = Genre(name='Horror')
  genre36 = Genre(name='Humor and Comedy')
  

  db.session.add(genre1)
  db.session.add(genre2)
  db.session.add(genre3)
  db.session.add(genre4)
  db.session.add(genre5)
  db.session.add(genre6)
  db.session.add(genre7)
  db.session.add(genre8)
  db.session.add(genre9)
  db.session.add(genre10)
  db.session.add(genre11)
  db.session.add(genre12)
  db.session.add(genre13)
  db.session.add(genre14)
  db.session.add(genre15)
  db.session.add(genre16)
  db.session.add(genre17)
  db.session.add(genre18)
  db.session.add(genre19)
  db.session.add(genre20)
  db.session.add(genre21)
  db.session.add(genre22)
  db.session.add(genre23)
  db.session.add(genre25)
  db.session.add(genre28)
  db.session.add(genre29)
  db.session.add(genre32)
  db.session.add(genre33)
  db.session.add(genre34)
  db.session.add(genre36)
  
  db.session.commit()

def undo_seedgenres():
    db.session.execute('TRUNCATE genres RESTART IDENTITY CASCADE;')
    db.session.commit()
