from app.models import db, Review

def seed_reviews():
  review1 = Review(book_id=1, rating=4, user_id= 1, content='This was a good book')
  review2 =  Review(book_id=2, rating=4, user_id= 2, content='This was a good book')
  review3 =  Review(book_id=3, rating=4, user_id= 3, content='This was a good book')
  review4 =  Review(book_id=4, rating=4, user_id= 2, content="This was a good book")
  review5 =  Review(book_id=5, rating=4, user_id= 3, content="I really enjoyed the book. It was a wonderful read, and I couldn't put it down. The ending left me with many unanswered questions but I will definitely be looking forward to hearing more about the novel in the future.")
  review6 =  Review(book_id=6, rating=4, user_id= 3, content="You won't be able to put it down. I read the book in a day because I simply couldn't stop myself. The plot is exciting and fast paced, making for a gripping read.")
  review7 =  Review(book_id=7, rating=4, user_id= 2, content="I read How to Tell a Story's book and I can honestly say that it was one of the best books I have ever read. It has great, easy to follow instructions and deep insights into the art of story telling. I would recommend this book for anyone who wants to learn how to tell a story, or is just interested in the process.")
  review8 =  Review(book_id=8, rating=4, user_id= 4, content="This book is a must-read for anyone wanting to learn the art of storytelling. The author goes into detail about how to create stories and then shares many examples from famous authors. I would recommend it to anyone looking to improve their writing skills, and I can't wait to incorporate what I've learned in my own writing!")
  review9 =  Review(book_id=9, rating=4, user_id= 4, content="I loved We Were Dreamers because it is so inspiring and beautifully written. The story of two siblings who are trying to make a difference in their world, even if it means being different. It was heartwarming to see the bond that the two had with each other and how they would do anything for each other. I had a hard time putting this book down because I wanted")
  review10 =  Review(book_id=10, rating=4, user_id= 4, content="I absolutely love Make Your Bed. It's one of the most inspirational books I've read in years. I loved how it made me want to do something that I had always put off, making my bed! It also helped me realize that small changes can lead to big successes.")
  review11 =  Review(book_id=11, rating=4, user_id= 4, content="I am an avid reader and usually really enjoy books. However, I found myself struggling to get through this one. The writing style was difficult to follow and the characters were not as compelling as they could have been.")
  review12 =  Review(book_id=12, rating=4, user_id= 4, content="This book is a must read! It's amazing how simple tricks can make such a big difference in your everyday life. I found that I was able to get more done in a day just by following these simple steps. And the best part: it only takes about ten minutes of your time each day!")
  review13 =  Review(book_id=13, rating=4, user_id= 4, content="Atomic Habits is a book that I have applied in my own life and it has become my go-to when I need to focus on self-improvement. With practical, research-backed advice and a clear path to success, this is the best personal development book I've ever read.")
  review14 =  Review(book_id=14, rating=4, user_id= 4, content="This book is a must read for anyone who thinks or feels stuck in their life. It will help you find your true path and pave it with love, kindness and forgiveness. I found my new best friend in this book.")
  review15 =  Review(book_id=15, rating=4, user_id= 3, content="I'm so glad I found this book. It is unlike anything I've read before. The story is told through letters to a friend and the writing style is beautiful. The story jumps off the page and into your heart. You'll laugh, you'll cry, and you'll feel as though you're right there with the family...it's like being home!")
  review16 =  Review(book_id=16, rating=4, user_id= 3, content="The Midwife of Auschwitz is a harrowing, beautifully written and important book that gives us insight into the perspective of a woman who has been largely ignored by history. Much more than just maternity caretaker, Gisella Perl's story begins with her escape from the Warsaw Ghetto and continues with her painful journey to Auschwitz-Birkenau. Her arrival marks the beginning of a")
  review17 =  Review(book_id=17, rating=4, user_id= 3, content="I am a mother of four and I have read this book several times. It is not a book you can read quickly, it's one that needs to be savored. The author dug deep into the human experience in ways I didn't know possible. She had me in tears and brought me back to life again with every page turn.")
  review18 =  Review(book_id=18, rating=4, user_id= 3, content="This was a good book")
  review19 =  Review(book_id=19, rating=4, user_id= 2, content="This was a good book")
  review20 =  Review(book_id=20, rating=4, user_id= 2, content="This was a good book")
  review21 =  Review(book_id=21, rating=4, user_id= 2, content="This was a good book")
  review22 =  Review(book_id=22, rating=4, user_id= 1, content="This was a good book")

  db.session.add(review1)
  db.session.add(review2)
  db.session.add(review3)
  db.session.add(review4)
  db.session.add(review5)
  db.session.add(review6)
  db.session.add(review7)
  db.session.add(review8)
  db.session.add(review9)
  db.session.add(review10)
  db.session.add(review11)
  db.session.add(review12)
  db.session.add(review13)
  db.session.add(review14)
  db.session.add(review15)
  db.session.add(review16)
  db.session.add(review17)
  db.session.add(review18)
  db.session.add(review19)
  db.session.add(review20)
  db.session.add(review21)
  db.session.add(review22)
  
  db.session.commit()

def undo_seedreviews():
    db.session.execute('TRUNCATE reviews RESTART IDENTITY CASCADE;')
    db.session.commit()
